# Generated by Django 2.1.dev20180309075957 on 2018-03-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=25)),
                ('adress', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('birthday', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
